site_name: python3教程
nav:
  - Home: index.md
  - "1. 第一课": first.md
  - "2. varibale 变量": variable.md
  - "3. 变量类型": variable-type.md
  - "4. input 输入": input.md
  - "5. print 再学": print2.md
  - "6. OJ 输入与 A+B": oj-input.md
  - "7. 练习 1": practice1.md
  - "8. if 双分支": if.md
  - "9. if 单分支": if2.md
  - "10. if 多分支": if3.md
  - "11. if 练习": "if-practice.md"
  - "12. 逻辑表达式": "if-logic.md"
  - "13. for循环入门": "for-loop1.md"
  - "14. for循环2": "for-loop2.md"

theme:
  name: material
  navigation_depth: 2
  palette: 

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true


extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/contrib/auto-render.min.js
  - /javascripts/katex.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css
